
server:
   error:
      # This is an example project for developers. We could expose stacktrace
      include-stacktrace: always

spring:
   mvc:
      static-path-pattern: /static/**
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:${user.home}/oidc-rp
      username: sa
      password: password
      initialization-mode: always
      initialize: true
      schema: classpath:/sql/schema.sql
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: none
      open-in-view: false
      show-sql: false
   h2:
      console:
         enabled: true
         path: /h2-console
         settings:
            trace: false
            web-allow-others: false


oidc:
   hosts:
      trust-anchor: 127.0.0.1
      cie-provider: 127.0.0.1
      relying-party: 127.0.0.1

   # required for onboarding checks and also for all the leafs
   default-trust-anchor: "http://${oidc.hosts.trust-anchor}:8000"

   # List of trust anchors
   trust-anchors:
   - ${oidc.default-trust-anchor}

   # Map of known OPs and related Trust Anchor.
   spid-providers:
     - subject: "http://${oidc.hosts.trust-anchor}:8000/oidc/op"
       trust-anchor: ${oidc.default-trust-anchor}
   cie-providers:
     - subject: "http://${oidc.hosts.cie-provider}:8002/oidc/op"
       trust-anchor: ${oidc.default-trust-anchor}

   relying-party:
      application-name: "SpringBoot RP Sample"
      application-type: "web"
      contacts:
      - "dev@example.com"
      #response-types  only "code" allowed
      scope:
      - openid
      - offline_access
      token-endpoint-auth-method: "private_key_jwt"
      id-token-signed-response-alg: "RS256"
      userinfo-signed-response-alg: "RS256"
      userinfo-encrypted-response-alg: "RSA-OAEP-256"
      userinfo-encrypted-response-enc: "A128CBC-HS256"

      federation-resolve-endpoint: "http://${oidc.hosts.relying-party}:8080/resolve"
      organization-name: "PA OIDC Relying Party"
      homepage-uri: "http://${oidc.hosts.relying-party}:8080/oidc/rp/landing"
      policy-uri: "http://${oidc.hosts.relying-party}:8080/oidc/rp/policy"
      logo-uri: "http://${oidc.hosts.relying-party}:8080/static/images/logo-it.svg"
      federation-contacts:
         - "federation-dev@example.com"

      client-id: "http://${oidc.hosts.relying-party}:8080/oidc/rp/"
      redirect-uris:
      - "http://${oidc.hosts.relying-party}:8080/oidc/rp/callback"
      jwk-fed-file-path: ${user.home}/oidc-rp-jwk.json
      jwk-core-file-path: ${user.home}/oidc-rp-core-jwk.json
      trust-marks-file-path: ${user.home}/oidc-rp-trust-marks.json
