# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# It also publish a SNAPSHOT artifact inside configured package repository
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HAVE_CODACY: ${{ secrets.CODACY_PROJECT_TOKEN != '' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11 PR
      if: github.event_name == 'pull_request'
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Set up JDK 11 Push
      if: github.event_name != 'pull_request'
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        server-id: github-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package -Pcoverage --file pom.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

    - name: Publish to GitHub Snapshot Packages
      if: github.event_name != 'pull_request'
      run: mvn deploy --batch-mode --errors --fail-at-end --show-version -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml
      env:
          GITHUB_TOKEN: ${{ github.token }}


